// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthInTaimer.Models;

public partial class User
{
    public int ID { get; set; }

    public string Name1 { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public int RoleID { get; set; }

    public int? FailedAttempts { get; set; }

    public bool IsAccountLocked { get; set; }
}